ALTER TABLE stores
    ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'system',
    ADD COLUMN edited_by VARCHAR(200) NOT NULL DEFAULT 'system';

ALTER TABLE correction_rules
    ADD COLUMN created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'system',
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN edited_by VARCHAR(200) NOT NULL DEFAULT 'system';

ALTER TABLE feedback
    ADD COLUMN created_at TIMESTAMPTZ,
    ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'system',
    ADD COLUMN updated_at TIMESTAMPTZ,
    ADD COLUMN edited_by VARCHAR(200) NOT NULL DEFAULT 'system';
UPDATE feedback SET created_at = submitted_at, updated_at = submitted_at WHERE created_at IS NULL OR updated_at IS NULL;
ALTER TABLE feedback
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN created_at SET DEFAULT CURRENT_TIMESTAMP,
    ALTER COLUMN updated_at SET NOT NULL,
    ALTER COLUMN updated_at SET DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE category_review_flags
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'system',
    ADD COLUMN edited_by VARCHAR(200) NOT NULL DEFAULT 'system';

ALTER TABLE feedback_notification_attempts
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'system',
    ADD COLUMN edited_by VARCHAR(200) NOT NULL DEFAULT 'system';

ALTER TABLE audit_events
    ADD COLUMN created_by VARCHAR(200) NOT NULL DEFAULT 'system',
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN edited_by VARCHAR(200) NOT NULL DEFAULT 'system';
